db:
    image: mongo:2.4
    restart: always
    command: /entrypoint.sh --smallfiles

sanap:
    image: eeacms/sanap:latest
    restart: always
    links:
        - db
    ports:
        - 5000:5000
    environment:
        - DEBUG=True
    volumes:
        - ./eea.sanap/sanap:/app/sanap
        - ./eea.sanap/libs:/app/libs
